version: "3.9"

services:
  web:
    image: nginx:latest
    restart: always
    volumes:
      - ./element-quiz.conf.template:/etc/nginx/templates/element-quiz.conf.template
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    environment:
      - PUBLIC_API_URL=$PUBLIC_API_URL
      - PUBLIC_FRONT_URL=$PUBLIC_FRONT_URL
      - PUBLIC_URL=$PUBLIC_URL
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db
      - front
      - api
    networks:
      - frontend-network
      - api-network

  db:
    image: postgres:14
    expose:
      - 5432:5432
    restart: always
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
    networks:
      - api-network
    

  front:
    build:
      context: ./front
      dockerfile: DockerfileProduction
    restart: always
    volumes:
      - ./front/src:/front/src
    expose:
      - "3000:3000"
    working_dir: /front
    command: serve -s build
    networks:
      - frontend-network

  api:
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    build: api
    restart: always
    volumes:
      - ./api/src:/api/src
    expose:
      - "4000:4000"
    working_dir: /api
    command: npm start
    networks:
      - api-network

volumes:
  db-store:

networks:
  frontend-network:
  api-network:
