version: "3.9"
services:
  web:
    image: nginx:latest
    volumes:
      - ./element-quiz.conf.template:/etc/nginx/templates/element-quiz.conf.template
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - PUBLIC_API_URL=$PUBLIC_API_URL
      - PUBLIC_URL=$PUBLIC_URL
    ports:
      - 80:80
    depends_on:
      - db
      - front
      - api
  db:
    image: postgres:14
    expose:
      - 5432:5432
    restart: always
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER

  front:
    build: 
      context: ./front
      dockerfile: DockerfileProduction
    restart: always
    volumes:
      - ./front/src:/front/src
    expose:
      - "3000:3000"
    working_dir: /front
    command: serve -s build

  api:
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    build: api
    restart: always
    volumes:
      - ./api/src:/api/src
    expose:
      - "4000:4000"
    working_dir: /api
    command: npm start

volumes:
  db-store:
